CREATE DATABASE MusicStore;
GO

USE MusicStore;
GO

CREATE TABLE tblArtist
(
Id INT NOT NULL IDENTITY (1, 1),
Name NVARCHAR(50) NOT NULL,
CONSTRAINT PK_tblArtist_ID PRIMARY KEY (Id)
);

CREATE TABLE tblAlbum
(
Id INT NOT NULL IDENTITY (1, 1),
ArtistId INT NULL,
Name NVARCHAR(50) NOT NULL,
[Year] INT NULL,
RatingAllMusicCom INT NULL
CONSTRAINT PK_tblAlbum_ID PRIMARY KEY (Id)
CONSTRAINT FK_tblAlbum_tblArtist FOREIGN KEY (ArtistId)
REFERENCES tblArtist(Id)
);

CREATE TABLE tblGenre
(
Id INT NOT NULL IDENTITY (1, 1),
Name NVARCHAR(50) NOT NULL,
CONSTRAINT PK_tblGenre_ID PRIMARY KEY(Id)
);

CREATE TABLE tblAlbumGenre
(
Id INT NOT NULL IDENTITY (1, 1),
AlbumId INT NOT NULL,
GenreID INT NOT NULL
CONSTRAINT PK_tblAlbumGenre_ID PRIMARY KEY (Id)
CONSTRAINT FK_tblAlbumGenre_tblAlbum FOREIGN KEY (AlbumID)
REFERENCES tblAlbum(Id),
CONSTRAINT FK_tblAlbumGerne_tblGerne FOREIGN KEY (GenreID)
REFERENCES tblGenre(Id)
); 

CREATE TABLE tblMusicShop
(
Id INT NOT NULL IDENTITY (1, 1),
CONSTRAINT PK_tblMusicShop_ID PRIMARY KEY (Id)
);

CREATE TABLE tblSeller
(
Id INT NOT NULL IDENTITY (1, 1),
ShopId INT NOT NULL,
Name NVARCHAR(50) NOT NULL,
Surname NVARCHAR(50) NOT NULL,
PassportID NVARCHAR(50) NOT NULL,
Birthday DATETIME NULL,
CONSTRAINT PK_tblSeller_ID PRIMARY KEY (Id),
CONSTRAINT FK_tblSeller_tblMusicShop FOREIGN KEY (ShopID)
REFERENCES tblMusicShop(Id)
);

CREATE TABLE tblSellerAuth
(
Id INT NOT NULL IDENTITY (1, 1),
[Login] NVARCHAR(50) NOT NULL,
[Password] VARCHAR(200) NOT NULL,
[Disabled] BIT NOT NULL
CONSTRAINT PK_tblSellerAuth_ID PRIMARY KEY (Id)
CONSTRAINT FK_tblSellerAuth_tblSeller FOREIGN KEY (Id)
REFERENCES tblSeller(Id)
);

CREATE TABLE tblCheck
(
Id INT NOT NULL IDENTITY (1, 1),
SellerId INT NOT NULL,
DateStatement DATETIME NOT NULL,
SumOverall DECIMAL(19, 2) NOT NULL
CONSTRAINT PK_tblCheck_ID PRIMARY KEY (Id)
CONSTRAINT FK_tblCheck_tblSeller FOREIGN KEY (SellerID)
REFERENCES tblSeller(Id)
);

CREATE TABLE tblSoldItem
(
Id INT NOT NULL IDENTITY (1, 1),
AlbumId INT NOT NULL,
CheckId INT NOT NULL,
SellDate DATETIME NOT NULL,
Amount INT NOT NULL,
SumItems DECIMAL(19, 2) NULL
CONSTRAINT PK_tblSoldItem_ID PRIMARY KEY (Id)
CONSTRAINT FK_tblSoldItem_tblCheck FOREIGN KEY (CheckID)
REFERENCES tblCheck(Id),
CONSTRAINT FK_tblSoldItem_tblAlbum FOREIGN KEY (AlbumID)
REFERENCES tblAlbum(Id)
);

CREATE TABLE tblAlbumsInShopStorage
(
Id INT NOT NULL IDENTITY (1, 1),
AlbumID INT NOT NULL,
MusicShopID INT NOT NULL,
Amount INT NOT NULL,
PriceBought INT NOT NULL,
PriceRealisation NUMERIC(19, 2) NOT NULL
CONSTRAINT PK_tblAlbumsInShopStorage_ID PRIMARY KEY (Id)
CONSTRAINT FK_tblAlbumsInShopStorage_tblAlbum FOREIGN KEY (AlbumID)
REFERENCES tblAlbum(Id),
CONSTRAINT FK_tblAlbumsInShopStorage_tblMusicShop FOREIGN KEY (MusicShopID)
REFERENCES tblMusicShop(Id)
);
GO